In [1]:
import os
import struct

In [69]:
dsift_feat = os.listdir('jpg.dsift/')
root = 'jpg.dsift/'
with open(root+dsift_feat[0], 'rb') as f:
    a = f.read(4)
    b = f.read()

In [27]:
a = struct.unpack('@i',a)
b = struct.iter_unpack('@128B4f',b)


In [33]:
def get_sift_vector(path):
    # read file and return list of sift vectors.
    with open(path, 'rb') as f:
        header = f.read(4)
        body = f.read()
    
    n_feats = struct.unpack('@i', header)
    feats = struct.iter_unpack('@128B4f', body)

    feat_list = [item[:-4] for item in feats]
    assert len(feat_list) == n_feats[0]

    return feat_list

img1_feat = get_sift_vector(root+dsift_feat[0])


In [68]:
class Img(object):

    # Img defined by sift descriptors

    def __init__(self, path):
        with open(path, 'rb') as f:
            header = f.read(4)
            body = f.read()
    
        n_feats = struct.unpack('@i', header)
        feats = struct.iter_unpack('@128B4f', body)

        feat_list = [item[:-4] for item in feats]
        assert len(feat_list) == n_feats[0]

        self.shape = np.array(feat_list).shape
        self.feats = np.array(feat_list)

In [70]:
img = Img(root+dsift_feat[0])

In [73]:
img.shape

(327, 128)

In [110]:
from collections import Counter

b = [1,1,1,2,2,2,4,4,7]
for i, v in Counter(b).items():
    print(i,v)

1 3
2 3
4 2
7 1


In [34]:
a = np.array(range(10)).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
np.argmax(a, axis=1)

array([4, 4])

In [32]:
print(np.argmax.__doc__)


    Returns the indices of the maximum values along an axis.

    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.

    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed.

    See Also
    --------
    ndarray.argmax, argmin
    amax : The maximum value along a given axis.
    unravel_index : Convert a flat index into an index tuple.

    Notes
    -----
    In case of multiple occurrences of the maximum values, the indices
    corresponding to the first occurrence are returned.

    Examples
    --------
    >>> a = np.arange(6).reshape(2,3) + 10
    >>> a
    array([[1

In [116]:
# 寻找矩阵每一列前k大值的行索引
a = np.random.randint(0,20,(10,10))
a

array([[19,  4,  7,  0,  9, 18, 15,  1,  3,  7],
       [ 8, 15, 16,  1,  4,  7,  7,  1,  5, 16],
       [ 4, 12, 12, 15, 18,  6, 10,  1, 13,  4],
       [ 4, 12,  0,  8, 12,  8,  7,  4, 19, 11],
       [15, 11, 11, 17, 12,  0,  2, 15, 17, 17],
       [10,  9, 16, 15,  3,  7, 11,  6,  8,  5],
       [14,  5,  7, 16,  6,  0, 15,  2,  9, 10],
       [ 9,  4,  5,  0,  0,  1, 14, 14,  6,  0],
       [ 3,  9,  8,  4,  3, 16,  4,  2, 18,  5],
       [ 4, 10,  5,  9,  5,  3,  0, 15,  8,  4]])

In [117]:
np.argpartition(a, -4, axis=1)[:,-4:]

array([[4, 6, 5, 0],
       [0, 1, 2, 9],
       [1, 8, 3, 4],
       [9, 1, 8, 4],
       [0, 3, 8, 9],
       [0, 6, 3, 2],
       [9, 6, 3, 0],
       [8, 0, 7, 6],
       [2, 1, 8, 5],
       [8, 3, 1, 7]])

In [122]:
np.random.randint(-1,10, size=4)

array([ 9, -1,  9,  3])

In [115]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
c = np.array([4,4,0,4,5,6,7,8,9,10])
np.minimum(b,c)

array([ 1,  2,  0,  4,  5,  6,  7,  8,  9, 10])

In [100]:
np.vstack([a, b])

array([[ 1,  8,  2, 15, 12, 12,  3,  1,  1,  4],
       [ 3,  1, 17, 14, 17,  0,  3, 14, 10,  6],
       [ 3, 17, 14, 13, 10, 19,  0,  3,  2, 13],
       [15,  7,  4,  1,  9,  0,  4, 10,  0,  4],
       [16,  6, 11, 18, 10, 11,  1,  2, 15,  4],
       [ 1,  1,  4,  0, 13, 14,  7, 16, 11,  3],
       [11, 16, 11,  3,  3,  9, 18,  5, 17, 12],
       [14,  4, 13,  2, 13,  0,  9, 10,  1, 19],
       [18,  4, 15,  7,  0, 19,  6, 10,  7, 13],
       [14, 16,  1, 16,  6,  9,  6, 13, 13, 18],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [44]:
ind = 56
res = np.array([45, 78, 21, 56, 57])

sum(res//4 == ind//4)

2

In [45]:
for i, row in enumerate(a):
    print(i,row)

0 [ 0 18  5  5  5  8 16 14  6  3]
1 [0 1 2 3 4 5 6 7 8 9]
2 [10 14 18  5  0  2  5  9 19 19]
3 [13  6  0 18 18  6 17 17  8 17]
4 [ 9 15  7  6  9  1 16  9  6  2]
5 [ 0  7  4 14  8  7 18  0 17  9]
6 [14  0  0 19 14  6  0 13  5  6]
7 [17  6 12  9  1 11 14  0  2  8]
8 [12 13 12 17  9 17  1  9  6  6]
9 [10  9 18  8 11  7  2  7 13  3]


In [54]:
def similarity_matrix(database):
 
    # return socre matrix S. S[i,j] means score of i and j
    score = np.zeros((len(database), len(database)))
    for i in range(len(database)):
        score[i] = [database[i].dot(each) for each in database]
    
    # import pickle
    # with open('score_matrix.pkl', 'wb') as f:
    #     pickle.dump(score_matrix)

    return score

In [57]:

s = similarity_matrix(a)

In [61]:
def evalute(similarity_matrix):

    top4 = np.argpartition(similarity_matrix, -4, axis=1)[:,-4:]
    print(top4)
    precision = [score(i, row) for i,row in enumerate(top4)]
    map = np.array(precision).mean()
    return map


def score(index, res):
    # index and res[]
    # calculate precision
    return sum(res//4 == index//4)

In [62]:
evalute(a)

[[5 7 6 1]
 [6 7 8 9]
 [1 2 8 9]
 [9 6 3 4]
 [0 6 1 4]
 [9 3 8 6]
 [7 0 3 4]
 [5 6 2 0]
 [2 1 5 3]
 [0 2 8 4]]


1.2

In [63]:
np.array([1, 0, 2, 1,2,1,2,2 ,0,1]).sum()

12

In [67]:
np.array([np.eye(3), np.ones((3,3))]).shape

(2, 3, 3)

In [123]:
import glob
import os
import pandas as pd

In [126]:
df = pd.DataFrame(a)
df

0   1   2   3   4   5   6   7   8   9
0  19   4   7   0   9  18  15   1   3   7
1   8  15  16   1   4   7   7   1   5  16
2   4  12  12  15  18   6  10   1  13   4
3   4  12   0   8  12   8   7   4  19  11
4  15  11  11  17  12   0   2  15  17  17
5  10   9  16  15   3   7  11   6   8   5
6  14   5   7  16   6   0  15   2   9  10
7   9   4   5   0   0   1  14  14   6   0
8   3   9   8   4   3  16   4   2  18   5
9   4  10   5   9   5   3   0  15   8   4

In [128]:
gb = df.groupby(0)
for name, grouped in gb:
    print(name)
    print(grouped)

3
   0  1  2  3  4   5  6  7   8  9
8  3  9  8  4  3  16  4  2  18  5
4
   0   1   2   3   4  5   6   7   8   9
2  4  12  12  15  18  6  10   1  13   4
3  4  12   0   8  12  8   7   4  19  11
9  4  10   5   9   5  3   0  15   8   4
8
   0   1   2  3  4  5  6  7  8   9
1  8  15  16  1  4  7  7  1  5  16
9
   0  1  2  3  4  5   6   7  8  9
7  9  4  5  0  0  1  14  14  6  0
10
    0  1   2   3  4  5   6  7  8  9
5  10  9  16  15  3  7  11  6  8  5
14
    0  1  2   3  4  5   6  7  8   9
6  14  5  7  16  6  0  15  2  9  10
15
    0   1   2   3   4  5  6   7   8   9
4  15  11  11  17  12  0  2  15  17  17
19
    0  1  2  3  4   5   6  7  8  9
0  19  4  7  0  9  18  15  1  3  7


In [133]:
res = gb.sum()
res

1   2   3   4   5   6   7   8   9
0                                     
3    9   8   4   3  16   4   2  18   5
4   34  17  32  35  17  17  20  40  19
8   15  16   1   4   7   7   1   5  16
9    4   5   0   0   1  14  14   6   0
10   9  16  15   3   7  11   6   8   5
14   5   7  16   6   0  15   2   9  10
15  11  11  17  12   0   2  15  17  17
19   4   7   0   9  18  15   1   3   7

In [142]:
(res.loc[3]-res.loc[4]*3).values


array([ -93,  -43,  -92, -102,  -35,  -47,  -58, -102,  -52])

In [145]:
d = res.loc[3].values

In [147]:
a = np.sum

In [148]:
a([1,2,4])

7